version: '3.7'

services:
  quiz-api:
    container_name: quiz-api
    build: 
      context: ./quiz
      dockerfile: Dockerfile
    tty: true
    environment:
      - DEBUG=0
      - DB_HOST=quiz-db
      - POSTGRES_DB=quiz-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && uvicorn quiz.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - ./quiz/static:/usr/src/quiz/static
      - ./quiz/media:/usr/src/quiz/media

    depends_on:
      db:
        condition: service_healthy
    ports:
      - 7777:8000

  db:
    container_name: quiz-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=quiz-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]

