# Generated by Django 4.2.3 on 2023-07-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('hard', 'hard')], max_length=300, null=True)),
                ('subject', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Math', 'Math')], max_length=300, null=True)),
                ('text', models.TextField()),
                ('answer', models.CharField(help_text='Must be identical to answers added below', max_length=300)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('hard', 'hard')], max_length=300, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_question_answer', to='tests.question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
